version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: mai033/kubevx:2.0
    ports:
      - "3001:3001"
      - "7070:7070"
    depends_on:
      - mongo
    environment:
      MONGO_URI: 'mongodb+srv://kubevx:letmein123@cluster0.zvkmoiz.mongodb.net/?retryWrites=true&w=majority'

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
