# global:
#   scrape_interval: 15s

# scrape_configs:
#   - job_name: 'eks-cluster'
#     kubernetes_sd_configs:
#       - role: pod
#     relabel_configs:
#       - source_labels: [__meta_kubernetes_pod_label_app]
#         action: keep
#         regex: webapp
