# global:
#   scrape_interval: 30s
#   scrape_timeout: 10s

# rule_files:
#   - alert.yml

# scrape_configs:
#   - job_name: services
#     metrics_path: /metrics
#     static_configs:
#       - targets:
#           - 'prometheus:9090'
#           - 'node-exporter:9100'
#           - 'host.docker.internal'

# alerting:
#   alertmanagers:
#     - scheme: http
#       static_configs:
#         - targets: ['alertmanager:9093']



apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 10s

    rule_files:
      - alert.yml  

    scrape_configs:
      - job_name: services
        metrics_path: /metrics
        static_configs:
          - targets:
              - 'prometheus:9090'
              - 'node-exporter:9100'
              - 'host.docker.internal'

    alerting:
      alertmanagers:
        - scheme: http
          static_configs:
            - targets: ['alertmanager:9093']

